# Aula 5 - Introdução às Bibliotecas Python e Numpy 🚀

## 🎯 Objetivos da Aula

Nesta aula, você aprenderá:

- 📚 A importância e a funcionalidade das bibliotecas em Python.
- 🔍 A diferença entre atributos e métodos em bibliotecas.
- 🧮 Como utilizar a biblioteca **Numpy (Numerical Python)** para manipulação e operações eficientes com arrays e matrizes numéricas.

## 🗂️ Estrutura da Aula

1. **O que são Bibliotecas em Python?** 📦
    - Definição e importância.
    - Como instalar e importar bibliotecas.
2. **Atributos e Métodos: Conceitos Fundamentais** ⚙️
    - Diferença entre atributos e métodos.
    - Exemplos práticos em bibliotecas populares.
3. **Explorando a Biblioteca Numpy** 🧑‍💻
    - Instalação e importação do Numpy.
    - Estrutura básica dos arrays Numpy.
    - Operações matemáticas comuns com Numpy.
    - Prática: Criando e manipulando arrays.

## 📚 Material Complementar (Opcional)
1. 🔎 Pesquise sobre a biblioteca **Numpy**.
2. 📖 Leia a documentação oficial.
3. ✏️ Entenda algum método ou função específica.
4. 💻 Replique com um código de teste.

🔗 [Documentação Numpy](https://numpy.org/doc/stable/)

---

## **O que são Bibliotecas em Python? 📦**

Bibliotecas em Python são conjuntos de funções, métodos e classes que facilitam a realização de tarefas específicas. Elas permitem reutilizar código escrito por outros, acelerando o desenvolvimento e evitando retrabalho.

Python inclui funções *builtin* — ou seja, funções nativas que vêm com a instalação da linguagem, como a conhecida `print()`, e bibliotecas padrão, como `math`, que oferece operações matemáticas úteis. 

O uso de bibliotecas torna o código mais eficiente, legível e modular.

In [2]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [3]:
dir(print)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [4]:
import math

help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [5]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [6]:
math.pi

3.141592653589793

In [7]:
from math import pi

pi

3.141592653589793

#### **Como instalar e importar bibliotecas?**

Para instalar bibliotecas em Python, você pode utilizar o gerenciador de pacotes `pip`. Basta executar o comando:

`pip install nome_da_biblioteca`

Tanto no terminal, quanto na célula jupyter com uma `!` antes.

In [145]:
# Não é uma biblioteca built-in, então temos que instalar para importar

!pip install numpy

In [9]:
# Importar a biblioteca toda

import numpy

In [10]:
# De uma biblioteca importar algo específico

from numpy import array

In [11]:
# Alias for numpy (as)

import numpy as np

#### **Como fazer minhas próprias bibliotecas?**

Você pode criar suas próprias bibliotecas em Python, organizando funções e classes em arquivos `.py`. Para utilizá-las, basta importar o arquivo no seu código principal.

In [13]:
# Altere 'minha_biblioteca' para o nome da sua biblioteca
import minha_biblioteca

dir(minha_biblioteca)

['Matematica',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'pi',
 'saudar']

In [14]:
help(minha_biblioteca)

Help on module minha_biblioteca:

NAME
    minha_biblioteca

CLASSES
    builtins.object
        Matematica

    class Matematica(builtins.object)
     |  Matematica(num1, num2)
     |
     |  Methods defined here:
     |
     |  __init__(self, num1, num2)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  divisao(self)
     |
     |  multiplicacao(self)
     |
     |  soma(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    saudar(nome)

DATA
    pi = 3.14159265359

FILE
    c:\users\andre\onedrive\documentos\github\fea-usp\fea dev\minha_biblioteca.py




In [15]:
minha_biblioteca.pi

3.14159265359

## O que são Atributos e Métodos? ⚙️

Em Python, atributos e métodos são elementos de classes e objetos que armazenam informações e realizam ações, respectivamente.

- **Atributos**: São variáveis associadas a um objeto ou classe, que armazenam informações sobre o objeto. Podem ser acessados com a notação de ponto (`objeto.atributo`).

- **Métodos**: São funções associadas a um objeto ou classe, que realizam ações específicas. Podem ser chamados com a notação de ponto (`objeto.metodo()`).

Exemplo:

```python
class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome  # Atributo
        self.idade = idade  # Atributo

    def apresentar(self):
        print(f"Olá, meu nome é {self.nome} e tenho {self.idade} anos.")  # Método

# Criando um objeto da classe Pessoa
pessoa1 = Pessoa("André", 23)

print(pessoa1.nome)  # Acessando o atributo 'nome'

pessoa1.apresentar()  # Chamando o método 'apresentar'
```

### **Porque tem essa matéria difícil aqui? 🤔**

Não precisa aprender a escrever atributos e métodos, mas sim a utilizá-los.

Isso é essencial para trabalhar com bibliotecas e entender como elas funcionam.

In [31]:
from datetime import datetime

# Método now da classe datetime
agora = datetime.now()
agora

datetime.datetime(2024, 11, 5, 22, 54, 49, 922325)

In [32]:
# Atributos da classe datetime
print("Ano:", agora.year)
print("Mês:", agora.month)
print("Dia:", agora.day)
print("Hora:", agora.hour)
print("Minuto:", agora.minute)
print("Segundo:", agora.second)
print("Microsegundo:", agora.microsecond)

Ano: 2024
Mês: 11
Dia: 5
Hora: 22
Minuto: 54
Segundo: 49
Microsegundo: 922325


## **Numpy:** Manipulação de Arrays e Matrizes 🧑‍💻

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMrTWz33b86nfIrgaW9jE_t-7VCcqJtjL-pg&s"></img>

**Numpy** é uma biblioteca Python amplamente utilizada para manipulação eficiente de arrays e matrizes numéricas. Ela oferece funções e métodos otimizados para:

1. Operações matemáticas
2. Estatísticas
3. Álgebra linear
4. Machine Learning
5. Processamento de Imagens
6. E muito mais!

### Por que usar Numpy?

- **Eficiência**: Numpy é implementado em C, o que o torna mais rápido que listas e arrays padrão do Python.
- **Facilidade de uso**: Oferece funções e métodos simples e intuitivos para operações com arrays.
- **Compatibilidade**: É amplamente utilizado em bibliotecas de análise de dados, aprendizado de máquina, processamento de imagens, entre outros.

### **Instalação e Importação do Numpy**

Para instalar o Numpy, você pode utilizar o `pip`:

```python
!pip install numpy
```

Para importar o Numpy, utilize o comando `import`:

```python
import numpy as np
```

### **Estrutura básica dos arrays Numpy**

Os arrays Numpy são estruturas de dados multidimensionais que armazenam elementos de um mesmo tipo. Eles são semelhantes às listas do Python, mas mais eficientes e rápidos.

<img src="https://www.pythontutorial.net/wp-content/uploads/2022/08/what-is-numpy-1024x572.png" width="750"></img>

### Por que arrays são mais rápidas que listas?

- **Homogeneidade**: Arrays Numpy armazenam elementos de um mesmo tipo, o que permite operações vetorizadas.
- **Memória contígua**: Os elementos de um array Numpy são armazenados em blocos de memória contíguos, facilitando o acesso e a manipulação.

<img src="https://i.ytimg.com/vi/FQbbkCFWNjY/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGDEgUihyMA8=&rs=AOn4CLBf7esvUoxbn0ZGYMRDVreVDVuyEg"></img>

In [169]:
# Listas vs. NumPy Arrays
from tqdm import tqdm
import time
import random

start = time.time()
# Listas
lista = []
for i in tqdm(range(10_000_000)):
    lista.append(random.randint(1, 100))
    
end = time.time()

print("Tempo de execução com listas:", end - start, "segundos")

100%|██████████| 10000000/10000000 [00:07<00:00, 1333366.48it/s]

Tempo de execução com listas: 7.714174747467041 segundos


In [175]:
import numpy as np

start = time.time()

# NumPy Arrays

array = np.random.randint(1, 100, 10_000_000)

end = time.time()

print("Tempo de execução com NumPy Arrays:", end - start, "segundos")

Tempo de execução com NumPy Arrays: 0.102386474609375 segundos


#### Básico de Numpy

In [ ]:
# Carregar a biblioteca numpy
import numpy as np

In [21]:
# Fazendo uma array com numpy
a = np.array([1, 2, 3], dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [146]:
# Array com vários tipos de dados

np.array(["FEA.dev", 1, 2.0, True])

array(['FEA.dev', '1', '2.0', 'True'], dtype='<U32')

In [10]:
# Array 2D

b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Pegar dimensão da array
print("Dimensão Array 1D: ", a.ndim)

print("Dimensão Array 2D: ", b.ndim)

Dimensão Array 1D:  1
Dimensão Array 2D:  2


In [ ]:
# Pegar o shape da array
print("Shape Array 1D: ", a.shape)

print("Shape Array 2D: ", b.shape)

Shape Array 1D:  (3,)
Shape Array 2D:  (2, 3)


In [ ]:
# Pegar o tipo de dado da array
# Tentar especificar o tipo de dado da array
print("Tipo Array 1D: ", a.dtype)

print("Tipo Array 2D: ", b.dtype)

Tipo Array 1D:  int32
Tipo Array 2D:  int32


In [ ]:
# Ver o bytes da array por item
print("Tamanho Array 1D: ", a.itemsize)

print("Tamanho Array 2D: ", b.itemsize)

Tamanho Array 1D:  4
Tamanho Array 2D:  4


In [ ]:
# Ver o tamanho da array
print("Tamanho Array 1D: ", a.size)

print("Tamanho Array 2D: ", b.size)

Tamanho Array 1D:  3
Tamanho Array 2D:  6


In [20]:
# Ver o quanto de memória a array ocupa
print("Memória Array 1D: ", a.nbytes)

print("Memória Array 2D: ", b.itemsize * b.size)
print("Memória Array 2D: ", b.nbytes)

Memória Array 1D:  12
Memória Array 2D:  24
Memória Array 2D:  24


#### Acessando elementos

In [23]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a.shape)
print(a)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
# Escolher elemento específico: [linha, coluna]

print(a[1, 3])
print(a[1, -2])

9
9


In [26]:
# Pegar linha específica

a[0, :]

array([1, 2, 3, 4, 5])

In [28]:
# Pegar coluna específica

a[:, 2]

array([3, 8])

In [33]:
# Intervalar: [inicio:fim:passo]

a[0, 1:4:2]

array([2, 4])

In [34]:
# Alterar elemento

a[1, 4] = 20
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

In [37]:
# Alterar coluna

a[:, 2] = 1 # ou [1, 2] se quiser alterar mais de um elemento
a

array([[ 1,  2,  1,  4,  5],
       [ 6,  7,  1,  9, 20]])

In [40]:
# Dica: Para saber como acessar um elemento específico, comece de dentro para fora, então comece com a linha, depois da coluna, e assim por diante.

# Desafio: Criar uma array 3x3 com 1s na diagonal principal e 0s no resto sem usar funções prontas do numpy

#### Inicializando arrays

In [45]:
# Array de zeros

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# Array de uns

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# Array com números específicos

np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [50]:
# Podemos reutilizar o shape de outra array

np.full_like(a, 4) # ou np.full(a.shape, 4)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [51]:
# Array com números aleatórios

np.random.rand(3, 3)

array([[0.73611656, 0.77643355, 0.54426914],
       [0.49352602, 0.45372726, 0.83333287],
       [0.47085948, 0.08154396, 0.23462569]])

In [52]:
# Array com números aleatórios inteiros

np.random.randint(0, 10, size=(3, 3))

array([[2, 2, 6],
       [0, 4, 1],
       [1, 3, 2]])

In [53]:
# Array identidade

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Range do numpy: np.arange(inicio, fim, passo)

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [127]:
# Intervalo com quantidade de elementos: np.linspace(inicio, fim, quantidade)

np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
# Cuidado ao copiar arrays

a = np.array([1, 2, 3])

b = a
b[0] = 350

print(a)

[350   2   3]


#### Operações matemáticas

In [58]:
a = np.array([1, 2, 3])

a + 2

array([3, 4, 5])

In [155]:
# Diferença com listas
a_lista = [1, 2, 3]

# a_lista + 2 # Erro

for i in range(len(a_lista)):
    a_lista[i] += 2

print("Normal: ", a_lista)

# Ou com list comprehension

a_lista = [1, 2, 3]

a_lista = [i + 2 for i in a_lista]
print("Com List Comprehension: ", a_lista)

Normal:  [3, 4, 5]
Com List Comprehension:  [3, 4, 5]


In [59]:
a - 2

array([-1,  0,  1])

In [60]:
a * 2

array([2, 4, 6])

In [61]:
a / 2

array([0.5, 1. , 1.5])

In [64]:
b = np.array([1, 0, 2])

a + b

array([2, 2, 5])

In [66]:
a * b

array([1, 0, 6])

#### Estatísticas

In [75]:
a = np.array([1, 2, 3, 2])

In [76]:
np.sum(a)

8

In [77]:
np.min(a)

1

In [78]:
np.max(a)

3

In [79]:
np.mean(a)

2.0

In [80]:
np.median(a)

2.0

#### Reorganizando arrays

In [ ]:
antes = np.array([[1, 2, 3], [4, 5, 6]])
print(antes.shape)
antes

(2, 3)
[[1 2 3]
 [4 5 6]]


In [97]:
depois = antes.reshape((3, 2))

print(depois.shape)
depois

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [178]:
# Transforma a array em uma array 1D
antes.flatten()

array([1, 2, 3, 4, 5, 6])

In [179]:
# Array Transposta
antes.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Filtrando arrays e indexação booleana

In [99]:
array = np.random.randint(0, 200, size=(3, 4))

array

array([[186,  11, 155, 139],
       [ 57, 168,  34,  88],
       [133, 171,  65, 110]])

In [100]:
array > 20

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
array[array > 20]

array([186, 155, 139,  57, 168,  34,  88, 133, 171,  65, 110])

In [ ]:
(array > 20) & (array < 100)

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [ ]:
array[(array > 20) & (array < 100)]

array([34, 88])

In [ ]:
(array < 25) | (array > 100)

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

In [ ]:
array[(array < 25) | (array > 100)]

array([186, 155, 139, 168,  34,  88, 133, 171, 110])

In [160]:
~(array % 2 == 0)

array([[False,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [161]:
array[~(array % 2 == 0)]

array([ 11, 155, 139,  57, 133, 171,  65])

In [112]:
np.any(array > 100) # axis=0 (coluna) ou 1 (linha)

True

In [117]:
np.any(array < 20, axis=1)

array([ True, False, False])

In [142]:
np.where(array > 100, array, 0)

array([[186,   0, 155, 139],
       [  0, 168,   0,   0],
       [133, 171,   0, 110]])

In [124]:
np.all(array > 60, axis=1)

array([False, False,  True])

## Desafio da Aula:

1. Crie um array Numpy com 10 elementos inteiros aleatórios entre 0 e 100 e com esse formato (2, 3).
2. Calcule a média, mediana e desvio padrão dos elementos (Dica: desvio-padrão == np.std()).
3. Substitua os elementos menores que a média pelo valor 0.

---

Isso **NÃO** é a lista da aula, é apenas um desafio para te estimular a utilizar o que aprendemos em aula